Broke my app by copying carousel files into public-events folder and private-events folder, and modifying carousel file names to include -pub and -pri. Gulp is throwing these errors: app/pages/private-events/carousel/carousel-pri.component.ts(102,13): error TS2304: Cannot find name 'ImagesPri'. app/pages/private-events/private-events.component.ts(7,9): error TS2305: Module '/Users/lindsaybrown/dev/Lynzphotos2016/app/pages/private-events/carousel/carousel-pri.component' has no exported member 'ImagesPri'. app/pages/public-events/carousel/carousel-pub.component.ts(102,13): error TS2304: Cannot find name 'ImagesPub'. app/pages/public-events/public-events.component.ts(15,13): error TS2304: Cannot find name 'Images'.